<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\OzonCard.Common.Infrastructure.Database\OzonCard.Common.Infrastructure.Database.csproj" />
      <ProjectReference Include="..\OzonCard.Database.Migrations.Postgres\OzonCard.Database.Migrations.Postgres.csproj" />
      <ProjectReference Include="..\OzonCard.Database.Migrations.SqlServer\OzonCard.Database.Migrations.SqlServer.csproj" />
    </ItemGroup>


   
</Project>
